version: "3.0"

services:
  web:
    build: .
    entrypoint: mix phx.server
    ports:
      - 4000:4000
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - "db:db"
    env:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/aicacia_events
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - state:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  state:
